
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Abled' do



pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase'
pod 'Firebase/Storage'
pod 'Firebase/Auth'


end
