# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Abled' do

end

target 'AbledTests' do

end

target 'AbledUITests' do

end

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'GooglePlaces'
pod 'GoogleMaps'

